name: Scrape latest help

on:
  workflow_dispatch:
  schedule:
    - cron:  '3 15 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Scrape Fly
      run: |-
        ./fly.sh
        # Grab the GraphQL schema too
        npx get-graphql-schema https://api.fly.io/graphql > flyctl/fly.graphql
    - name: Scrape AWS
      run: |-
        python -m pip install -U awscli
        python -m awscli --version > aws/aws-version.txt
        cat aws/aws-version.txt
        python aws_commands.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
