name: Scrape latest help

on:
  workflow_dispatch:
  schedule:
    - cron:  '3 15 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Configure Git for commits
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        sudo chown -R runner:runner /run/systemd/resolve/stub-resolv.conf
        sudo echo nameserver 8.8.8.8 > /run/systemd/resolve/stub-resolv.conf
    - name: Use Griffe to scrape sqlite-utils
      run: |-
        bash zstd.sh
    - name: Commit and push if it changed
      run: |-
        git add -A
        timestamp=$(date -u)
        git commit -m "zstd: ${timestamp}" || exit 0
        git push
    - name: Use Griffe to scrape sqlite-utils
      run: |-
        bash ffmpeg.sh
    - name: Commit and push if it changed
      run: |-
        git add -A
        timestamp=$(date -u)
        git commit -m "ffmpeg: ${timestamp}" || exit 0
        git push
    

